### ISSUE TITLE
Cursor Color

### ISSUE THREAD

**Issue by EgZvor** [afq984/base16-xfce4-terminal#1]
Instead of actual color, it should be

> ColorCursor=

or else the cursor text is often invisible.
![cursorcolor](https://cloud.githubusercontent.com/assets/11237935/18113060/f12bae22-6f3d-11e6-852f-2ce9a6db1724.png)

**Comment by afq984** [comment]
The issue you reported is valid

However, If the color is not specified, it will be `#00AA00`

are you suggesting that the `ColorCursor` should not be specified, or, the color should be different from the one for white?

Please note also, this problem exist even with the built-in theme "Dark Pastels".

**Comment by EgZvor** [comment]
If I change `terminalrc` file in `~/.config/xfce4/terminal`. It's not `#00AA00`, but the same as selection, i.e. inversive, which is not very good also, I guess.

**Comment by afq984** [comment]
I guess if the color is not specified, it will fallback to other sources.

If there's any other base16 color code suitable for the purpose, I'm happy to change.

**Comment by lufte** [comment]
Sorry to revive this old issue but I have to agree with @EgZvor, setting ColorCursor to an empty value (both on the theme and terminalrc) paints the character under the cursor with the inverse color so it's always readable. It does require to do extra configuration besides installing the themes, which is not ideal, but with the themes as they are the character under the cursor is almost impossible to see.

Another option is to, for each theme, set the cursor color to a slightly lighter tone of the background color (I used the same color and added 20 to its "Value" using the default XFCE color picker). Since most of the colors will have a pretty good contrast with the background color, it will work pretty well for the cursor too.

**Comment by afq984** [comment]
@lufte I can not reproduce your statements about inverse colors.
This is what I get when I left ColorCursor empty:
![image](https://user-images.githubusercontent.com/4318379/27759167-fdf95168-5dee-11e7-8650-d12dc58dc3b5.png)
What does xfce4-terminal output for you?

**Comment by lufte** [comment]
When I leave ColorCursor empty in the configuration file, XFCE preferences dialog shows what seems to be a random color. As soon as I change the preset, the color defaults to #00AA00 (I have set ColorCursor to an empty value to all my presets as well) and the `ColorCursor=` line gets removed from the file. It seems the preferences dialog considers an empty value invalid so it removes it, but you can see the behavior I describe if you select your preset (with `ColorCursor=`) and set `ColorCursor=` on terminalrc after that. Here's a screenshot of what I mean, right side being the inverse color thing.

EDIT: Now that I look closely it's not really an "inverse color", it's just the cursor getting the color of the character, and the character set to black.
![untitled](https://user-images.githubusercontent.com/7890579/27759497-9ecb46aa-5e08-11e7-81c2-746715e13249.png)

**Comment by afq984** [comment]
I'll look for a way to make it available in the theme file

**Comment by afq984** [comment]
In the color scheme file (something like `~/.local/share/xfce4/terminal/colorschemes/foo.theme`)
set `ColorCursor` to an invalid color e.g.
```
[Scheme]
ColorCursor=x
```
As it is not empty, xfce4-termial won't overwrite it with the defualt value, and instead copy the invalid color to terminalrc. With an invalid color, the cursor will be the said "inverted color"
@lufte can you confirm whether this method works for you?

Notes
* [terminal_preferences_get_color](https://git.xfce.org/apps/xfce4-terminal/tree/terminal/terminal-preferences.c?h=xfce4-terminal-0.8.5.1&id=6cae486b8765f91141cbcad0124e4b99ccd595cd#n1636) returns false when it cannot parse the color
* If has_cursor is false, [NULL is passed to vte_terminal_set_color_cursor](https://git.xfce.org/apps/xfce4-terminal/tree/terminal/terminal-screen.c?h=xfce4-terminal-0.8.5.1&id=6cae486b8765f91141cbcad0124e4b99ccd595cd#n1037)
* And in vte_terminal_set_color_cursor, [If NULL, text under the cursor will be drawn with foreground and background colors reversed](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-color-cursor)

**Comment by lufte** [comment]
Works like a charm!
