### ISSUE TITLE
What is the diff between default.16 and default templates?

### ISSUE THREAD

**Issue by joshgoebel** [afq984/base16-xfce4-terminal#10]
I didn't see at a glance.

**Comment by afq984** [comment]
The built-in theme xfce4-terminal provides uses a combination of colors + lighter colors.
However most base16 schemes use grayscale (base00-base07) + colors (base08-base0f) for the palette. 
This maps poorly to xfce4-terminal's default. Hence the two versions:
* `default` to look similar to xfce4-terminal's built-in default theme, which does not use all the colors from a scheme.
* `default.16` to map all colors from a scheme.

![image](https://user-images.githubusercontent.com/4318379/178130569-56dc6af6-b2ea-4c85-8de2-fec3a7b9a0f0.png)

**Comment by joshgoebel** [comment]
Thanks I think I follow now!
