### ISSUE TITLE
Colors in "nord" theme don't match color slots

### ISSUE THREAD

**Issue by dlueke** [afq984/base16-xfce4-terminal#3]
Hi,

I recently went through the color schemes and noticed that the colors in the "nord" theme don't match the color slots of the xfce terminal.
This is quite irritating when your terminal displays information via different colors.
Is this intentional or a mistake?
For the latter case I have rearranged the existing colors to match the proper color slots (with the orange color in the purple color slot):

rearranged existing colors:
`#2E3440;#BF616A;#A3BE8C;#EBCB8B;#5E81AC;#D08770;#88C0D0;#E5E9F0;#4C566A;#BF616A;#A3BE8C;#EBCB8B;#5E81AC;#D08770;#88C0D0;#8FBCBB`

Alternatively here are the colors from the original nord-theme which can be found here:
https://github.com/arcticicestudio/nord-xfce-terminal

original nord colors:
`#3B4252;#BF616A;#A3BE8C;#EBCB8B;#81A1C1;#B48EAD;#88C0D0;#E5E9F0;#4C566A;#BF616A;#A3BE8C;#EBCB8B;#81A1C1;#B48EAD;#8FBCBB;#ECEFF4`

Redards
Dominik

**Comment by afq984** [comment]
Currently, the theme here is generated by the following process:

1. A user create a base16 [scheme repo](https://github.com/8-uh/base16-nord-scheme), specifying the *16 bases*
2. The scheme is submitted to the [scheme list](https://github.com/chriskempson/base16-schemes-source)
3. The scheme is built according to the [template](https://github.com/afg984/base16-xfce4-terminal/tree/master/templates) in this repo

The template here tries to follow xfce4-terminal's original palette designs as close as possible.
The order of the 16 bases are given in the order that makes:

> the palette of the generated **Base16-Solarized Dark.16**
> _exactly the same as_
> the palette of the bulit-in **solarized (dark)** 

As a result of (1) and (3), the color palette does not match the one in nord-xfce-terminal.

---

I think if there's a theme from the original theme author, we can always prefer that over the base16-generated version. As the former tend to be more carefully picked, while the later is generated from a general rule.

**Comment by afq984** [comment]
There's nothing to do on our (template source) side
