### ISSUE TITLE
What scheme(s) best approximate ANSI 4-bit colour

### ISSUE THREAD

**Issue by HaleTom** [afq984/base16-xfce4-terminal#7]
What scheme(s) would best represent [ANSI 4-bit colour](https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit)?

Default seems to have too many greys.

**Comment by afq984** [comment]
As per [base16 styling guidelines version 0.2] half of the colors are meant to be grey (in `.16.theme`). If that is undesired, use the `.theme` variants.

[base16 styling guidelines version 0.2]: http://chriskempson.com/projects/base16/#styling-guidelines

**Comment by HaleTom** [comment]
Ok, I think I misunderstood the design philosophy.

For people wanting colourschemes that resemble ANSI, see here:

https://mayccoll.github.io/Gogh/
