### ISSUE TITLE
The move to base16-project Github organization

### ISSUE THREAD

**Issue by JamyGolden** [afq984/base16-xfce4-terminal#8]
Hi @afq984, there is a group of us working on reviving the base16 project and I'm wondering if you'd be willing to join.

The [discussion about a base16 Github organization](https://github.com/chriskempson/base16/issues/74) initially started in 2016. Now, with the disappearance of Chris Kempson, the importance of the [base16](https://github.com/base16-project/base16) organization is more vital than ever to keep the project structured and thriving. Currently there is a "deprecation" notice on the old [chriskempson/base16](https://github.com/chriskempson/base16) repo.

Seeing as you maintain this repo, we're [looking for more colaborators](https://github.com/base16-project/base16/issues/2) and I was wondering if you are you interested in joining [github.com/base16-project](https://github.com/base16-project) and helping us maintain some of the projects?

Right now, logistical communication around this is happening at https://github.com/base16-project/base16/issues/1. Some of us are also on #base16 on Libera Chat [IRC] (for more general discussions and hangouts)

Are you interested in maintaining any [base16-project](https://github.com/base16-project) repositories and being part of the organization?

**Comment by afq984** [comment]
I can help with the builders and the CI if there's a need (as an example, you can see this repo is bot-maintained since Dec 2020)

**Comment by JamyGolden** [comment]
Thanks for offering that. It's really helpful to have a bot updating automatically! Definitely one of the things that makes template repos fall out of date easily.

We've got a bot running on all our template repos https://github.com/base16-project/base16-emacs/blob/main/.github/workflows/update.yml so we don't need help setting that up. We use [base16-builder-go](https://github.com/base16-project/base16-builder-go) to build the projects, which adheres to the latest [0.10.1](https://github.com/base16-project/home/blob/main/builder.md) builder spec.

There has been things going on in the project since I last messaged you : https://github.com/base16-project/home/issues/51

If you want this repo to live under the organization umbrella and be the primary maintainer, let me know and I'll add you to the organization and you can transfer the repo. 

I see you're using your own go builder; Even if you continue to work on this project independently, I recommend using [base16-builder-go](https://github.com/base16-project/base16-builder-go) to make sure your themes are always adhering to the latest spec.

**Comment by afq984** [comment]
> If you want this repo to live under the organization umbrella and be the primary maintainer, let me know and I'll add you to the organization and you can transfer the repo.

Sounds good to me.

**Comment by JamyGolden** [comment]
Great, I've sent an invite. You should be able to transfer once you've accepted.

**Comment by afq984** [comment]
Done
